[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT main:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[envs]
SESSION_SECRET = "taskmanager-secret-key"